export default theme = {
  //   ltr: "",
  //   rtl: "",
  //   placeholder: "",
  paragraph: "mb-4",
  //   quote: "",
  //   heading: {
  //     h1: "",
  //     h2: "",
  //     h3: "",
  //     h4: "",
  //     h5: "",
  //   },

  // potentially we can fix list item maker styles for admin editor in a seperate theme.

  list: {
    // nested: {
    //   listitem: "",
    // },
    ol: "pl-5 list-decimal",
    ul: "pl-5 list-disc",
    // listitem: "",
  },
  //   image: "",
  link: "underline text-blue-500 hover:text-blue-400 transition-colors",
  text: {
    bold: "font-bold",
    italic: "italic",
    // overflowed: "",
    // hashtag: "",
    underline: "underline",
    // strikethrough: "",
    // underlineStrikethrough: "",
    // code: "",
  },
  // code: "",
  // codeHighlight: {
  //    atrule: "",
  //    attr: "",
  //    boolean: "",
  //    builtin: "",
  //    cdata: "",
  //    char: "",
  //    class: "",
  //    "class-name": "",
  //    comment: "",
  //    constant: "",
  //    deleted: "",
  //    doctype: "",
  //    entity: "",
  //    function: "",
  //    important: "",
  //    inserted: "",
  //    keyword: "",
  //    namespace: "",
  //    number: "",
  //    operator: "",
  //    prolog: "",
  //    property: "",
  //    punctuation: "",
  //    regex: "",
  //    selector: "",
  //    string: "",
  //    symbol: "",
  //    tag: "",
  //    url: "",
  //    variable: "",
  //},
};
